name: My_first_workflow

on:
  push:
    branches: 
      - main
    
jobs:
   hello_world:
      runs-on: ubuntu-latest
      
      steps:
      - name: Clone Git repo
        uses: action/checkout@v1
        
      - name: View files
        run: ls -la
        
      - name: view dockerfile
        run: cat Dockerfile
