name: My_first_workflow

on:
  push:
    branches: 
      - main
    
jobs:
   hello_world:
      runs-on: ubuntu-latest
      
      steps:
      - name: View Hello World!
        run: echo "Hello World!"
